const ActionType = {
  SET_STATE: 'SET_STATE',
  DELETE_STATE: 'DELETE_STATE',
  ADD_DIALOG: 'ADD_DIALOG',
  DISMISS_DIALOG: 'DISMISS_DIALOG',
  REMOVE_DIALOG: 'REMOVE_DIALOG',
  UPDATE_DIALOG: 'UPDATE_DIALOG'
};

export default ActionType;