const OrderStatus = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  DELETED: 'DELETED'
};

export default OrderStatus;