const S = {
  th: {
    SLOGAN: 'จำหน่ายอุปกรณ์นิวเมติกส์ทุกชนิด',
    SEARCH_PRODUCT: 'ค้นหาสินค้า',
    FEATURED_PRODUCT: 'สินค้ายอดฮิต',
    CATEGORIES: 'ประเภทสินค้า',
    CATEGORY: 'ประเภทสินค้า',
    BRANDS: 'ยี่ห้อสินค้า',
    BRAND: 'ยี่ห้อสินค้า',
    MENU_HOME: 'หน้าหลัก',
    MENU_SEARCH: 'ค้นหาสินค้า',
    MENU_ORDER: 'ออเดอร์',
    MENU_REFUND: 'คืนเงิน',
    MENU_CAT: 'ประเภทสินค้า',
    MENU_BRAND: 'ยี่ห้อสินค้า',
    MENU_ABOUT: 'เกี่ยวกับเรา',
    MENU_CONTACT: 'ติดต่อเรา',
    MENU_ADDRESS: 'ที่อยู่จัดส่ง',
    MENU_LANGUAGE: 'Change Langugae',
    BTN_LOGIN: 'ลงชื่อเข้าใช้',
    BTN_REGISTER: 'ลงทะเบียน',
    ADDRESS: 'ที่อยู่',
    TAMBON: 'แขวง/ตำบล',
    DISTRICT: 'เขต/อำเภอ',
    PROVINCE: 'จังหวัด',
    POSTCODE: 'รหัสไปรณีย์',
    REMOVE: 'ลบออก',
    NO_ADDRESS: 'ไม่มีข้อมูลที่อยู่',
    ADD_ADDRESS: 'เพิ่มที่อยู่',
    KEYWORD: 'คำค้นหา',
    SEARCH: 'ค้นหา',
    DISMISS: 'ยกเลิก',
    PENDING_REVIEW: 'รอการตรวจสอบ/ถูกยกเลิก',
    ACCEPTED: 'รับออเดอร์แล้ว',
    DELIVERED: 'จัดส่งแล้ว',
    COMPLETED: 'ได้รับสินค้าแล้ว',
    DELETED: 'ออเดอร์ยกเลิก',
    APPLY_FOR_REFUND: 'ขอคืนเงิน',
    DELETE_WITHOUT_REFUND: 'ลบออเดอร์',
    DELETE_ORDER: 'ลบออเดอร์',
    THB: 'บาท',
    ORDER_ID: 'ออเดอร์ไอดี',
    ORDER_STATUS: 'สถานะ',
    ORDER_SUBMITTED: 'วันที่ซื้อ',
    ORDER_ITEMS: 'สินค้า',
    ORDER_PRICE: 'ราคารวม',
    ORDER_STATUS_PENDING_REVIEW: 'รอการตรวจสอบ',
    ORDER_STATUS_REJECTED: 'ถูกยกเลิก',
    ORDER_STATUS_ACCEPTED: 'รอการจัดส่ง',
    ORDER_STATUS_DELIVERED: 'จัดส่งแล้ว',
    ORDER_STATUS_COMPLETED: 'ได้รับสินค้าแล้ว',
    ORDER_STATUS_PENDING_REFUND: 'รอการคืนเงิน',
    ORDER_STATUS_DELETED: 'ลบแล้ว'
  },
  en: {
    SLOGAN: 'One stop hub for pneumatic products',
    SEARCH_PRODUCT: 'search product',
    FEATURED_PRODUCT: 'Featured Products',
    CATEGORIES: 'Product Categories',
    CATEGORY: 'Category',
    BRANDS: 'Product Brands',
    BRAND: 'Brand',
    MENU_HOME: 'Home',
    MENU_SEARCH: 'Search',
    MENU_ORDER: 'My Orders',
    MENU_REFUND: 'Refund',
    MENU_CAT: 'Categories',
    MENU_BRAND: 'Brands',
    MENU_ABOUT: 'About Us',
    MENU_CONTACT: 'Contact Us',
    MENU_ADDRESS: 'My Addresses',
    MENU_LANGUAGE: 'เปลี่ยนภาษา',
    BTN_LOGIN: 'Login',
    BTN_REGISTER: 'Register',
    ADDRESS: 'Address',
    TAMBON: 'Tumbon',
    DISTRICT: 'District',
    PROVINCE: 'Province',
    POSTCODE: 'Postal Code',
    REMOVE: 'delete',
    NO_ADDRESS: 'No Address',
    ADD_ADDRESS: 'Add Address',
    KEYWORD: 'Keyword',
    SEARCH: 'Search',
    DISMISS: 'Dismiss',
    PENDING_REVIEW: 'Pending Review',
    ACCEPTED: 'Accepted',
    DELIVERED: 'Delivered',
    COMPLETED: 'Completed',
    DELETED: 'Deleted',
    APPLY_FOR_REFUND: 'Apply For Refund',
    DELETE_WITHOUT_REFUND: 'Delete without Refund',
    DELETE_ORDER: 'Delete',
    THB: 'THB',
    ORDER_ID: 'Order ID',
    ORDER_STATUS: 'Status',
    ORDER_SUBMITTED: 'Order On',
    ORDER_ITEMS: 'Items',
    ORDER_PRICE: 'Total Price',
    ORDER_STATUS_PENDING_REVIEW: 'Pending Review',
    ORDER_STATUS_REJECTED: 'Rejected',
    ORDER_STATUS_ACCEPTED: 'Accepted',
    ORDER_STATUS_DELIVERED: 'Delivered',
    ORDER_STATUS_COMPLETED: 'Completed',
    ORDER_STATUS_PENDING_REFUND: 'Pending Refund',
    ORDER_STATUS_DELETED: 'Deleted'
  }
};

export default S;